[variables]
NIXPACKS_PHP_VERSION = "8.3"

[phases.install]
cmds = [
  "COMPOSER_ALLOW_SUPERUSER=1 APP_URL=http://localhost composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
  "APP_URL=http://localhost php artisan package:discover --ansi",
  "APP_URL=http://localhost php artisan config:cache",
  "APP_URL=http://localhost php artisan route:cache",
  "APP_URL=http://localhost php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
